const quotes = [
  "“Talk is cheap. Show me the code.” – Linus Torvalds",
  "“Programs must be written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
  "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
  "“First, solve the problem. Then, write the code.” – John Johnson",
  "“Experience is the name everyone gives to their mistakes.” – Oscar Wilde",
  "“In order to be irreplaceable, one must always be different.” – Coco Chanel",
  "“Java is to JavaScript what car is to Carpet.” – Chris Heilmann",
  "“Knowledge is power.” – Francis Bacon",
  "“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.” – Dan Salomon",
  "“Before software can be reusable it first has to be usable.” – Ralph Johnson",
  "“Make it work, make it right, make it fast.” – Kent Beck",
  "“The most disastrous thing that you can ever learn is your first programming language.” – Alan Kay",
  "“The best way to get a project done faster is to start sooner.” – Jim Highsmith",
  "“Simplicity is the soul of efficiency.” – Austin Freeman",
  "“Programs are meant to be read by humans and only incidentally for computers to execute.” – Donald Knuth",
  "“Good code is its own best documentation.” – Steve McConnell",
  "“Code never lies, comments sometimes do.” – Ron Jeffries",
  "“Fix the cause, not the symptom.” – Steve Maguire",
  "“Programming isn’t about what you know; it’s about what you can figure out.” – Chris Pine",
  "“The only way to learn a new programming language is by writing programs in it.” – Dennis Ritchie",
  "“Testing leads to failure, and failure leads to understanding.” – Burt Rutan",
  "“The computer was born to solve problems that did not exist before.” – Bill Gates",
  "“If debugging is the process of removing software bugs, then programming must be the process of putting them in.” – Edsger Dijkstra",
  "“You can't have great software without a great team.” – Joel Spolsky",
  "“Code is like humor. When you have to explain it, it’s bad.” – Cory House",
  "“Sometimes, the elegant implementation is just a function. Not a method. Not a class. Not a framework. Just a function.” – John Carmack",
  "“A good programmer is someone who always looks both ways before crossing a one-way street.” – Doug Linder",
  "“Deleted code is debugged code.” – Jeff Sickel",
  "“A language that doesn’t affect the way you think about programming is not worth knowing.” – Alan Perlis",
  "“Don’t comment bad code—rewrite it.” – Brian Kernighan",
  "“Programming is the art of algorithm design and the craft of debugging errant code.” – Ellen Ullman",
  "“Computers are good at following instructions, but not at reading your mind.” – Donald Knuth",
  "“The most important property of a program is whether it accomplishes the intention of its user.” – C.A.R. Hoare",
  "“Any sufficiently advanced bug is indistinguishable from a feature.” – Rich Kulawiec",
  "“Software is a gas; it expands to fill its container.” – Nathan Myhrvold",
  "“One man’s crappy software is another man’s full-time job.” – Jessica Gaston",
  "“The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.” – Seymour Cray",
  "“To iterate is human, to recurse divine.” – L. Peter Deutsch",
  "“Programming is not easy like Sunday morning, it’s silent nights and coffee mornings.” – Unknown",
  "“There are only two kinds of programming languages: those people always complain about and those nobody uses.” – Bjarne Stroustrup",
  "“The best thing about a boolean is even if you are wrong, you are only off by a bit.” – Anonymous",
  "“Don't worry if it doesn't work right. If everything did, you’d be out of a job.” – Mosher’s Law of Software Engineering",
  "“You should name a variable using the same care with which you name a first-born child.” – Robert C. Martin",
  "“Premature optimization is the root of all evil.” – Donald Knuth",
  "“The function of good software is to make the complex appear to be simple.” – Grady Booch",
  "“Software testing is a sport like hunting, it's bug hunting.” – Amit Kalantri",
  "“Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else.” – Eagleson’s Law",
  "“Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots.” – Rick Cook",
  "“Programming is like writing a book… except if you miss out a single comma on page 126 the whole thing makes no sense.” – Unknown"
];

function generateQuote() {
  const quoteElement = document.getElementById("quote");
  const randomIndex = Math.floor(Math.random() * quotes.length);
  quoteElement.textContent = quotes[randomIndex];
}
